"""CTC BMS register map - GENERATED, do not hand-edit.

Source: "User Manual-BMS Manual-16260016.pdf" (CTC, 2026-02-02), tables on
pages 24-44. Regenerate with dev/scripts/parse_bms.py then
dev/scripts/gen_registers.py.

Protocol (from the manual): registers live above 49999, read with FC03, write
with FC16, offset 0, max 100 registers per transfer.

The map has three shapes, which is how you split it into Home Assistant
devices: SYSTEM_REGISTERS (one controller), HP_FIELDS (x10 heat pumps) and
ZONE_FIELDS (x4 heating systems). device_registers() does that split for you.

dtype: S/U = signed/unsigned, 16/32 = width. A 32-bit value spans TWO registers
stored LSB first, MSB second (value = MSB << 16 | LSB) - little-endian word
order, the opposite of the usual Modbus convention.

access: R = read-only, RW = writable setpoint. This tool never writes; RW rows
are here so you can READ how the pump is configured.

unit: INFERRED from the description - the manual gives only a scale factor - so
treat units as a hint, not gospel.
"""

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class Reg:
    number: int
    name: str
    desc: str = ''
    dtype: str = 'S16'      # S16 | U16 | S32 | U32
    scale: float = 0.1
    unit: str = '°C'
    access: str = 'R'       # R | RW
    device: str = 'System'  # System | HP1..HP10 | Zone1..Zone4

    @property
    def count(self) -> int:
        """Registers to read: 32-bit values span two."""
        return 2 if self.dtype.endswith('32') else 1


@dataclass(frozen=True)
class ArrayField:
    """A field repeated once per heat pump / zone: member n is at
    base + (n-1)*stride.
    """
    field: str
    base: int
    stride: int
    dtype: str
    scale: float
    unit: str
    access: str
    desc: str


MAX_HEAT_PUMPS = 10
MAX_ZONES = 4


def _renumber(desc: str, n: int) -> str:
    """The manual writes every array row out for member 1; renumber for n."""
    desc = re.sub(r'Heat pump 1 \(A1\)', f'Heat pump {n} (A{n})', desc)
    desc = re.sub(r'Heating system 1', f'Heating system {n}', desc)
    desc = re.sub(r'\bHP1\b', f'HP{n}', desc)
    desc = re.sub(r'Compressor 1\b', f'Compressor {n}', desc)
    return re.sub(r'(room temp) 1\b', rf'\1 {n}', desc)


def _materialise(fields, n, label):
    return [
        Reg(f.base + (n - 1) * f.stride, f'{label} {f.field}',
            _renumber(f.desc, n), f.dtype, f.scale, f.unit, f.access, label)
        for f in fields
    ]


# --- per-heat-pump fields (HP1..HP10) --------------------------------------
# HP4's brine-out is 62097 + 3 = 62100 - exactly the register the community HA
# integration mislabels as 'heat pump status'. Real status is HP1 Status/62017.
HP_FIELDS = [
    ArrayField('Blocked', 61521, 1, 'S16', 1.0, '', 'RW',
               "Heat pump 1 (A1): Blocked 0=Blocked, 1=Allowed"),
    ArrayField('RPSMax', 61572, 1, 'S16', 0.1, 'rps', 'RW',
               "Heat pump 1 (A1): Max RPS"),
    ArrayField('Status', 62017, 1, 'S16', 1.0, '', 'R',
               "Heat pump 1 (A1): Status 0=Compressor_off_start_delay, 1=Compressor_of"),
    ArrayField('TempIn', 62027, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1) HP in"),
    ArrayField('TempOut', 62037, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1) HP out"),
    ArrayField('DischargeGas', 62047, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1): Discharge temperature"),
    ArrayField('SuctionGas', 62057, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1): Suction gas temperature"),
    ArrayField('HighPressure', 62067, 1, 'S16', 0.1, 'bar', 'R',
               "Heat pump 1 (A1): High pressure"),
    ArrayField('LowPressure', 62077, 1, 'S16', 0.1, 'bar', 'R',
               "Heat pump 1 (A1): Low Pressure"),
    ArrayField('BrineTempIn', 62087, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1): Brine in"),
    ArrayField('BrineTempOut', 62097, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1): Brine out"),
    ArrayField('ChargePump', 62107, 1, 'S16', 0.1, '%', 'R',
               "Heat pump 1 (A1): Charge pump"),
    ArrayField('BrinePump', 62117, 1, 'S16', 0.1, '%', 'R',
               "Heat pump 1 (A1): Brine pump"),
    ArrayField('Fan', 62127, 1, 'S16', 0.1, '%', 'R',
               "Heat pump 1 (A1): Fan"),
    ArrayField('DefrostTimer', 62137, 1, 'S16', 1.0, '', 'R',
               "Heat pump 1 (A1): Defrost timer"),
    ArrayField('OutsideTemp', 62147, 1, 'S16', 0.1, '°C', 'R',
               "Heat pump 1 (A1): Outdoor temp"),
    ArrayField('SWVersion', 62157, 1, 'S16', 1.0, '', 'R',
               "Heat pump 1 (A1): Software version"),
    ArrayField('CurrRPS', 62193, 1, 'S16', 0.1, 'rps', 'R',
               "Heat pump 1 (A1): Current RPS"),
    ArrayField('CompressorTime', 62214, 2, 'U32', 1.0, 'h', 'R',
               "State: Compressor 1 operating time LSB"),
    ArrayField('CompressorTime24H', 62234, 1, 'U16', 1.0, 'h', 'R',
               "State: Compressor 1 last 24h"),
    ArrayField('Type', 62254, 1, 'S16', 1.0, '', 'R',
               "Heat pump 1 (A1) type"),
    ArrayField('CompressorModel', 62264, 1, 'S16', 1.0, '', 'R',
               "Heat pump 1 (A1) compressor model"),
    ArrayField('PrimarySystemFlow', 62291, 1, 'S16', 0.1, 'l/min', 'R',
               "Heat pump 1 (A1) Primary system flow"),
    ArrayField('PowerConsumption', 62331, 1, 'U16', 0.1, 'kW', 'R',
               "HP1 Power consumption kW"),
    ArrayField('Energy', 62341, 2, 'U32', 1.0, 'kWh', 'R',
               "Compressor 1 Power consumption kWh LSB"),
]

# --- per-heating-system fields (zones 1..4) --------------------------------
ZONE_FIELDS = [
    ArrayField('SetPoint', 61509, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: setting room temp"),
    ArrayField('Inclination', 61513, 1, 'S16', 0.1, '', 'RW',
               "Heating system 1: Change inclination"),
    ArrayField('Adjustment', 61517, 1, 'S16', 0.1, '', 'RW',
               "Room1: Adjustment"),
    ArrayField('PrimaryFlowMax', 61534, 1, 'S16', 0.1, '', 'RW',
               "Heating system 1: Max Primary flow ° C"),
    ArrayField('PrimaryFlowMin', 61538, 1, 'S16', 0.1, '', 'RW',
               "Heating system 1: Min primary flow ° C 140=Off"),
    ArrayField('Mode', 61542, 1, 'S16', 1.0, '', 'RW',
               "Heating system 1: Heating mode 0=Auto, 1=On, 2=Off"),
    ArrayField('HeatingOffTemp', 61546, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: Heating off, out ° C"),
    ArrayField('HeatingOffTime', 61550, 1, 'S16', 1.0, 'h', 'RW',
               "Heating system 1: Heating off time"),
    ArrayField('ReduceTempNight', 61554, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: Room temp night reduction"),
    ArrayField('PrimaryFlowReduceNight', 61558, 1, 'S16', 0.1, '', 'RW',
               "Heating system 1: Primary flow Night reduction"),
    ArrayField('NightReduceOffTemp', 61562, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: Outdoor temp night reduction"),
    ArrayField('AlarmLowRoomTemp', 61566, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: Alarm low room temperature"),
    ArrayField('ReduceTempVac', 61602, 1, 'S16', 0.1, '°C', 'RW',
               "Heating system 1: Holiday reduction"),
    ArrayField('PrimaryFlowReduceVac', 61606, 1, 'S16', 0.1, '', 'RW',
               "Heating system 1: Primary flow Holiday reduction"),
    ArrayField('HeatingOnTime', 61725, 1, 'S16', 1.0, 'h', 'RW',
               "Heating system 1: Heating on time"),
    ArrayField('Temp', 62007, 1, 'S16', 0.1, '°C', 'R',
               "Heating system 1: Temperature setpoint primary flow"),
    ArrayField('PrimaryFlow', 62011, 1, 'S16', 0.1, '°C', 'R',
               "Heating system 1: Primary flow temperature"),
    ArrayField('TempCurr', 62203, 1, 'S16', 0.1, '°C', 'R',
               "Current room temp 1"),
    ArrayField('Status', 62246, 1, 'S16', 1.0, '', 'R',
               "Heating system 1 status 0 = Heating off, 1 = Vacation, 2= Night reduct"),
    ArrayField('ShuntState', 62308, 1, 'U16', 1.0, '', 'R',
               "Heating system 1: Shunt state 0 = Close, 1 = Inactive, 2 = Open"),
]


def registers_for_hp(n: int) -> list[Reg]:
    """Registers for heat pump `n` (1-based)."""
    if not 1 <= n <= MAX_HEAT_PUMPS:
        raise ValueError(f'heat pump must be 1..{MAX_HEAT_PUMPS}, got {n}')
    return _materialise(HP_FIELDS, n, f'HP{n}')


def registers_for_zone(n: int) -> list[Reg]:
    """Registers for heating system / zone `n` (1-based)."""
    if not 1 <= n <= MAX_ZONES:
        raise ValueError(f'zone must be 1..{MAX_ZONES}, got {n}')
    return _materialise(ZONE_FIELDS, n, f'Zone{n}')


# --- system-wide registers (neither per-pump nor per-zone) ------------------
SYSTEM_REGISTERS = [
    Reg(61500, 'sDHWMode', "Hot water mode 0=Ecomony, 1=Normal, 2=Comfort",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61501, 'sDHWManStopTemp', "Manual Stop temperature hot water",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61502, 'sDHWTempOut', "Setting outlet temperature hot water",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61503, 'sDHWTimerExtra', "Extra hot water timer",
        'S16', 0.5, '', 'RW', 'System'),
    Reg(61504, 'HeatMaxTime', "Maximum time heating Heat pump",
        'S16', 1.0, 'h', 'RW', 'System'),
    Reg(61505, 'sDHWMaxTime', "Maximum time hot water",
        'S16', 1.0, 'h', 'RW', 'System'),
    Reg(61506, 'sDHWMinRPS', "Minimum RPS hot water",
        'S16', 0.1, 'rps', 'RW', 'System'),
    Reg(61507, 'sPoolMinRPS', "Minimum RPS Pool",
        'S16', 0.1, 'rps', 'RW', 'System'),
    Reg(61508, 'sVacationDaysTimer', "Number of vacation days timer",
        'S16', 1.0, 'days', 'RW', 'System'),
    Reg(61531, 'poolTempStopSetting', "Pool: Stop Temp setting",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61532, 'poolMaxTime', "Pool: Maximum time",
        'S16', 1.0, 'h', 'RW', 'System'),
    Reg(61533, 'poolDiffStart', "Pool: Start difference",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61570, 'hsChargePumpSetting', "Radiator pump setting %",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61571, 'hpDMStart', "Start at degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61582, 'exb1DMStart', "E1: Start add heat, degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61583, 'exb1Diff', "External boiler diff",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61584, 'exbBlockOutTemp', "Blocking additional heat outdoor temp ºC",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61585, 'exbBoilerShuntTemp', "Boiler , open mixing valve ºC",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61586, 'exbBoilerDelayStop', "Delay stop external boiler",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61587, 'exbMode', "Ext boiler mode 0=Auto, 1=On, 2=Off",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61588, 'ehsStartDegrees', "EHS: open shunt degrees",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61589, 'ehsDiffStartStop', "EHS: start / stop diff",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61590, 'elhMaxPower', "Max immersion heater kW / Lower",
        'S16', 0.1, 'kW', 'RW', 'System'),
    Reg(61591, 'elhDHWMaxPower', "Max immersion heater DHW kW / Upper",
        'S16', 0.1, 'kW', 'RW', 'System'),
    Reg(61610, 'hpXDMDiff', "Heat pump : Diff Heat pump , degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61611, 'hpXDMDelay', "Heat pump : Delay between Heat pump",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61612, 'ex1DMDiff', "E1: Diff add heat, degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61613, 'ex2DMStart', "E2: Start 0-10V degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61614, 'ex2DMDiff', "E2: Diff 0-10V, degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61615, 'ex3DMStart', "E3: Start EcoMiniEl, degree minute",
        'S16', 1.0, 'DM', 'RW', 'System'),
    Reg(61616, 'ex3StepsHeat', "E3: Number of steps heating",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61617, 'ex3StepsDHW', "E3: Number of steps DHW",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61618, 'ex3EMEDiffSteps', "E3: Diff step EcoMiniEl",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61619, 'ex1Delay', "E1: Delay add heat E1",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61620, 'ex2Delay', "E2: Delay add heat 0-10V",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61621, 'ex2DiffDelay', "E2: Diff 0-10V delay",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61622, 'ex3EMEDelay', "E3: Delay EcoMiniEl",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61623, 'ex3EMEDelaySteps', "E3: Delay EcoMiniEl step",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61624, 'coolPrimaryOut20', "Cooling: Primary flow at the outdoor temperature +20 ºC",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61625, 'coolPrimaryOut40', "Cooling: Primary flow at the outdoor temperature +40 ºC",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61626, 'coolPrimaryMin', "Cooling: Min flow temperature",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61629, 'sMixValveDelaySet', "Delay mixing valve setting 241=Off",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61630, 'woodFlueGasTempStart', "Wood boiler start flue gas 490=Off",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61631, 'woodBoilerTempStart', "Wood boiler start boiler temperature",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61632, 'woodHysteresis', "Wood boiler hysteresis",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61633, 'elhLowerSetp', "Boiler lower °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61634, 'elhUpperSetp', "Boiler upper °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61635, 'elhAddHeatSetp', "Boiler add heat °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61636, 'elhDHWAddHeatSetp', "Boiler DHW °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61637, 'dthDiffTempStart', "Diff thermostat start temp diff",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61638, 'dthDiffTempStop', "Diff thermostat stop temp diff",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61639, 'dthChargeTemp', "Diff thermostat charge temperature",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61640, 'sunDiffTempStart', "EcoLogic / EcoZenith i550: Solar deltaT max Other: Solar start charge ",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61641, 'sunDiffTempStop', "EcoLogic / EcoZenith i550: Solar deltaT min Other: Solar stop charge d",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61642, 'sunChargePumpMin', "Solar charge pump min",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61643, 'sunDiffDrillTempStart', "EcoLogic / EcoZenith i550: Solar deltaT max borehole Other: Solar bore",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61644, 'sunDiffDrillTempStop', "EcoLogic / EcoZenith i550: Solar deltaT min borehole Other: Solar bore",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61645, 'sunMainTankChargeTemp', "EcoHeat 400 / EcoZenith i250: Solar H-tank charge temp GSi/EcoZenith i",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61646, 'sunExtraTankChargeTemp', "Solar: X-tank charge temp",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61647, 'sunEcoTankChargeTemp', "Solar: Eco-tank charge temp",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61648, 'sunMainTankDiffTempStart', "EcoHeat 400 / EcoZenith i250: Solar charge H-tank start difference GSi",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61649, 'sunMainTankDiffTempStop', "EcoHeat 400 / EcoZenith i250: Solar H-tank charge stop difference GSi/",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61650, 'sunMainTankTempStop', "EcoHeat 400 / EcoZenith i250: Solar H-tank charge stop temperature GSi",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61651, 'woodTankReturnDelay', "Wood boiler buffer tank delay recharge time",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61652, 'sElHeaterTankUpperSetp', "Setpoint for upper tank when el. heater is used",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61653, 'sDHWCapacityStart', "Capacity start point for charging DHW",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61654, 'sDHWLowerStartTemp', "Lower temp sensor start point for charging DHW",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61655, 'sVentilationMode', "Ventilation mode",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61656, 'sVentNightcoolValue', "Turn night cooling on or off",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61657, 'sVentAwayMode', "Ventilation away mode",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61658, 'pool_enable', "Pool Enable",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61659, 'room_temp_cooling', "Room temp cooling",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61660, 'cooling_permitted_from_outdoor_temp_c', "Cooling permitted from outdoor temp °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61661, 'cooling_delay_active_minutes', "Cooling delay active (minutes)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61662, 'delay_cooling_from_heating_off_minutes', "Delay cooling from heating off (minutes)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61663, 'cooling_start_delay_minutes', "Cooling start delay (minutes)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61664, 'cooling_diff_calc_delay_minutes', "Cooling diff calc delay (minutes)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61665, 'primary_flow_temp_at_outdoor_20_c', "Primary flow temp at outdoor +20 °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61666, 'primary_flow_temp_at_outdoor_40_c', "Primary flow temp at outdoor +40 °C",
        'S16', 0.1, '°C', 'RW', 'System'),
    Reg(61667, 'primary_flow_diff_at_outdoor_20_c', "Primary flow diff at outdoor +20 °C",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61668, 'primary_flow_diff_at_outdoor_40_c', "Primary flow diff at outdoor +40 °C",
        'S16', 0.1, '', 'RW', 'System'),
    Reg(61669, 'cooling_max_time_hp_active_minutes', "Cooling max time HP active (minutes)",
        'S16', 1.0, 'h', 'RW', 'System'),
    Reg(61670, 'cooling_hp_charge_pump_speed', "Cooling HP Charge pump speed",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61671, 'heating_program_hc1_0_economy_1_normal_2', "Heating program HC1 0 = Economy, 1 = Normal, 2 = Comfort, 3 = Custom",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61672, 'heating_program_hc2_0_economy_1_normal_2', "Heating program HC2 0 = Economy, 1 = Normal, 2 = Comfort, 3 = Custom",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61673, 'heating_program_hc3_0_economy_1_normal_2', "Heating program HC3 0 = Economy, 1 = Normal, 2 = Comfort, 3 = Custom",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61674, 'heating_program_hc4_0_economy_1_normal_2', "Heating program HC4 0 = Economy, 1 = Normal, 2 = Comfort, 3 = Custom",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61675, 'hc1_heating_curve_point_1_x_value_outsid', "HC1 Heating curve point 1 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61676, 'hc1_heating_curve_point_1_y_value_setp_t', "HC1 Heating curve point 1 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61677, 'hc1_heating_curve_point_2_x_value_outsid', "HC1 Heating curve point 2 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61678, 'hc1_heating_curve_point_2_y_value_setp_t', "HC1 Heating curve point 2 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61679, 'hc1_heating_curve_point_3_x_value_outsid', "HC1 Heating curve point 3 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61680, 'hc1_heating_curve_point_3_y_value_setp_t', "HC1 Heating curve point 3 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61681, 'hc1_heating_curve_point_4_x_value_outsid', "HC1 Heating curve point 4 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61682, 'hc1_heating_curve_point_4_y_value_setp_t', "HC1 Heating curve point 4 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61683, 'hc1_heating_curve_point_5_x_value_outsid', "HC1 Heating curve point 5 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61684, 'hc1_heating_curve_point_5_y_value_setp_t', "HC1 Heating curve point 5 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61685, 'hc2_heating_curve_point_1_x_value_outsid', "HC2 Heating curve point 1 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61686, 'hc2_heating_curve_point_1_y_value_setp_t', "HC2 Heating curve point 1 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61687, 'hc2_heating_curve_point_2_x_value_outsid', "HC2 Heating curve point 2 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61688, 'hc2_heating_curve_point_2_y_value_setp_t', "HC2 Heating curve point 2 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61689, 'hc2_heating_curve_point_3_x_value_outsid', "HC2 Heating curve point 3 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61690, 'hc2_heating_curve_point_3_y_value_setp_t', "HC2 Heating curve point 3 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61691, 'hc2_heating_curve_point_4_x_value_outsid', "HC2 Heating curve point 4 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61692, 'hc2_heating_curve_point_4_y_value_setp_t', "HC2 Heating curve point 4 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61693, 'hc2_heating_curve_point_5_x_value_outsid', "HC2 Heating curve point 5 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61694, 'hc2_heating_curve_point_5_y_value_setp_t', "HC2 Heating curve point 5 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61695, 'hc3_heating_curve_point_1_x_value_outsid', "HC3 Heating curve point 1 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61696, 'hc3_heating_curve_point_1_y_value_setp_t', "HC3 Heating curve point 1 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61697, 'hc3_heating_curve_point_2_x_value_outsid', "HC3 Heating curve point 2 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61698, 'hc3_heating_curve_point_2_y_value_setp_t', "HC3 Heating curve point 2 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61699, 'hc3_heating_curve_point_3_x_value_outsid', "HC3 Heating curve point 3 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61700, 'hc3_heating_curve_point_3_y_value_setp_t', "HC3 Heating curve point 3 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61701, 'hc3_heating_curve_point_4_x_value_outsid', "HC3 Heating curve point 4 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61702, 'hc3_heating_curve_point_4_y_value_setp_t', "HC3 Heating curve point 4 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61703, 'hc3_heating_curve_point_5_x_value_outsid', "HC3 Heating curve point 5 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61704, 'hc3_heating_curve_point_5_y_value_setp_t', "HC3 Heating curve point 5 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61705, 'hc4_heating_curve_point_1_x_value_outsid', "HC4 Heating curve point 1 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61706, 'hc4_heating_curve_point_1_y_value_setp_t', "HC4 Heating curve point 1 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61707, 'hc4_heating_curve_point_2_x_value_outsid', "HC4 Heating curve point 2 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61708, 'hc4_heating_curve_point_2_y_value_setp_t', "HC4 Heating curve point 2 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61709, 'hc4_heating_curve_point_3_x_value_outsid', "HC4 Heating curve point 3 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61710, 'hc4_heating_curve_point_3_y_value_setp_t', "HC4 Heating curve point 3 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61711, 'hc4_heating_curve_point_4_x_value_outsid', "HC4 Heating curve point 4 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61712, 'hc4_heating_curve_point_4_y_value_setp_t', "HC4 Heating curve point 4 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61713, 'hc4_heating_curve_point_5_x_value_outsid', "HC4 Heating curve point 5 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61714, 'hc4_heating_curve_point_5_y_value_setp_t', "HC4 Heating curve point 5 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61715, 'cooling_curve_point_1_x_value_outside_te', "Cooling curve point 1 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61716, 'cooling_curve_point_1_y_value_setp_temp', "Cooling curve point 1 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61717, 'cooling_curve_point_2_x_value_outside_te', "Cooling curve point 2 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61718, 'cooling_curve_point_2_y_value_setp_temp', "Cooling curve point 2 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61719, 'cooling_curve_point_3_x_value_outside_te', "Cooling curve point 3 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61720, 'cooling_curve_point_3_y_value_setp_temp', "Cooling curve point 3 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61721, 'cooling_curve_point_4_x_value_outside_te', "Cooling curve point 4 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61722, 'cooling_curve_point_4_y_value_setp_temp', "Cooling curve point 4 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61723, 'cooling_curve_point_5_x_value_outside_te', "Cooling curve point 5 x-value (outside temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(61724, 'cooling_curve_point_5_y_value_setp_temp', "Cooling curve point 5 y-value (setp temp)",
        'S16', 1.0, '', 'RW', 'System'),
    Reg(62000, 'sOutsideTemp', "Outdoor temperature",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62001, 'sStopTempDHW', "Stop temperature DHW",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62002, 'sSetPDHW', "Setpoint outlet temperature DHW",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62003, 'sDHWTemp', "Hot water temperature",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62004, 'sMixValveDelay', "Delay mixing valve",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62005, 'sStatus', "Status 0: HP upper , 1: HP lower , 2: Add 3: HP + Add, 4: HC, 5: DHW 6",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62006, 'sRadiatorTemp', "Radiator Water",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62015, 'sReturnTemp', "Return temp",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62016, 'sDHWPump', "DHW circulation",
        'S16', 1.0, '%', 'R', 'System'),
    Reg(62167, 'sDM', "Degree minute",
        'S16', 0.1, 'DM', 'R', 'System'),
    Reg(62168, 'sPowerConsumption', "Power kW immersion heater",
        'S16', 0.1, 'kW', 'R', 'System'),
    Reg(62169, 'sPowerConsumptionHS', "Power kW immersion heater lower",
        'S16', 0.1, 'kW', 'R', 'System'),
    Reg(62170, 'sCurrent', "Maximum current",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62171, 's1Current', "Current L1",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62172, 's2Current', "Current L2",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62173, 's3Current', "Current L3",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62174, 'sDiffThermostatPump', "Pump Diff thermostat",
        'S16', 1.0, '%', 'R', 'System'),
    Reg(62175, 'sDiffThermostatTemp', "Diff thermostat ° C",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62176, 'ehsTemp', "EHS: Temperature",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62177, 'ehsStatus', "EHS: Primary flow -> Mode",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62178, 'poolStatus', "Pool Mode",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62179, 'poolTemp', "Pool: Temperature",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62180, 'poolTempStop', "Pool: Stop temperature",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62181, 'sunStatus', "Solar: Mode 0=Off, 1=On",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62182, 'sunTempOut', "Solar: Temperature out",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62183, 'sunTempIn', "Solar: Temperature in",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62184, 'sunPump', "Solar: Pump panel",
        'S16', 1.0, '%', 'R', 'System'),
    Reg(62185, 'sTankTimer', "Tank Timer",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62186, 'sTotalTime', "Stat: Total Operation LSB",
        'U32', 1.0, 'h', 'R', 'System'),
    Reg(62191, 'sElHeaterConsumption', "Stat: Immersion heater kWh",
        'S16', 1.0, 'kWh', 'R', 'System'),
    Reg(62192, 'sFuncTest', "Function Test",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62207, 'sSystemType', "System Type",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62208, 'woodFlueGasTemp', "Wood: Flue gas temperature (B8)",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62209, 'woodBoilerTemp', "Wood: Temperature boiler (B9)",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62210, 'ex1BoilerTemp', "E1: Boiler temperature (B9)",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62211, 'ex1BoilerTempOut', "E1: Temperature boiler out (B10)",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62212, 'ex2Steps', "E2: Number of steps",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62213, 'ex3Status', "E3: Status",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62244, 'sSoftwareVersionMD', "Software version Display month day",
        'S16', 1.0, 'days', 'R', 'System'),
    Reg(62245, 'sSoftwareVersionYear', "Software version Display year",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62250, 'exbUpperTemp', "Ext buffer tank upper B41",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62251, 'exbLowerTemp', "Ext buffer tank lower B42",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62252, 'exbDHWTemp', "Ext DHW buffer tank B43",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62253, 'sProductType', "Product type",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62274, 'sTankLowerSetp', "Setpoint lower tank",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62275, 'sDHWLowerTemp', "Actual temperature DHW lower",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62276, 'sDHWUpperTemp', "Actual temperature DHW",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62277, 'sSunTankTemp', "Actual temperature tank solar coil",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62278, 'sElHeaterTankUpperCalcSetp', "Calculated setpoint for upper tank when el. heater is used",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62279, 'sDHWCapacity', "Current DHW capacity in percent",
        'S16', 0.1, '%', 'R', 'System'),
    Reg(62280, 'sFanExhaustPct', "Exhaust fan speed percent",
        'S16', 1.0, '%', 'R', 'System'),
    Reg(62281, 'sHighestCO2', "Highest measured CO2",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62282, 'sHighestRH', "Highest measured humidity",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62283, 'sVentMaintFilterDays', "Days until filter maintenance",
        'S16', 1.0, 'days', 'R', 'System'),
    Reg(62284, 'sVentNightcoolStatus', "Ventilation night cooling status",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62288, 'cooling_tank_setp', "Cooling tank setp",
        'S16', 0.1, '', 'R', 'System'),
    Reg(62289, 'cooling_tank_temp', "Cooling tank temp",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62290, 'active_cooling_return_temp', "Active cooling return temp",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62301, 'sgmode_0_none_normal_1_block_2_low_price', "SGMode 0 = None/Normal, 1 = Block, 2 = Low price, 3 = High cap",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62302, 'elspot_price_mwh_integer_currency_depend', "Elspot Price/MWh Integer (Currency depending on region)",
        'S16', 1.0, '', 'R', 'System'),
    Reg(62303, 'elspot_price_mwh_4_decimals', "Elspot Price/MWh 4 decimals",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62304, 'radiatorpump1', "RadiatorPump1",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62305, 'radiatorpump2', "RadiatorPump2",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62306, 'radiatorpump3_g3', "RadiatorPump3_G3",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62307, 'radiatorpump4_g4', "RadiatorPump4_G4",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62312, 'pumpg41_extern_dhw', "PumpG41 Extern DHW",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62313, 'hotwatervalve', "HotWaterValve",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62314, 'extboileron', "ExtBoilerOn",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62315, 'el1_relay_bit_0_a_bit_1_b', "EL1 Relay Bit 0: A, Bit 1: B",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62316, 'el2_relay_bit_0_a_bit_1_b', "EL2 Relay Bit 0: A, Bit 1: B",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62317, 'el3_relay_bit_0_a_bit_1_b', "EL3 Relay Bit 0: A, Bit 1: B",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62318, 'elheater3_6kw', "ElHeater3_6kW",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62319, 'evk_shunt_state_0_close_1_inactive_2_ope', "EVK: Shunt state 0 = Close, 1 = Inactive, 2 = Open",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62320, 'extboiler_shunt_state_0_close_1_inactive', "ExtBoiler: Shunt state 0 = Close, 1 = Inactive, 2 = Open",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62321, 'active_cooling_valve', "Active Cooling: Valve",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62322, 'active_cooling_demand', "Active Cooling: Demand",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62323, 'dhwpump_0_100', "DHWPump: 0-100",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62324, 'solartankselection', "SolarTankSelection",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62325, 'solarbedrockselection', "SolarBedrockSelection",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62326, 'hotwatervalve2', "HotWaterValve2",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62327, 'e4', "E4",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62328, 'e1', "E1",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62330, 'current_room_temp_cooling', "Current room temp cooling",
        'S16', 0.1, '°C', 'R', 'System'),
    Reg(62362, 'hbt_top_temp', "HBT top temp",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62363, 'dhw_tank_top_temp', "DHW tank top temp",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62364, 'cooling_tank_top_temp', "Cooling tank top temp",
        'U16', 1.0, '', 'R', 'System'),
    Reg(62365, 'periodic_extra_dhw_status_0_periodic_ext', "Periodic extra DHW status 0 = periodic extra DHW not defined 1 = perio",
        'U16', 1.0, '', 'R', 'System'),
]


def device_registers(hps=range(1, MAX_HEAT_PUMPS + 1),
                     zones=range(1, MAX_ZONES + 1)) -> dict[str, list[Reg]]:
    """The map split into Home Assistant devices: System, HP1.., Zone1.., in
    address order within each device.
    """
    devices = {'System': sorted(SYSTEM_REGISTERS, key=lambda r: r.number)}
    for n in hps:
        devices[f'HP{n}'] = registers_for_hp(n)
    for n in zones:
        devices[f'Zone{n}'] = registers_for_zone(n)
    return devices


def all_registers(hp: int = 1, zone: int = 1) -> list[Reg]:
    """System registers plus one heat pump and one zone, in address order."""
    regs = SYSTEM_REGISTERS + registers_for_hp(hp) + registers_for_zone(zone)
    return sorted(regs, key=lambda r: r.number)

